// Export movieCategories array for shared use

export const movieCategories = [
    {
      title: "Trending Now",
      movies: [
        {
          id: 1,
          movieId: "avatar-way-of-water",
          title: "Avatar: The Way of Water",
          image: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
          rating: "7.6",
          mood: ["epic", "visual-spectacle", "adventure"],
        },
        {
          id: 2,
          movieId: "top-gun-maverick",
          title: "Top Gun: Maverick",
          image: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
          rating: "8.3",
          mood: ["adrenaline", "nostalgic", "action-packed"],
        },
        {
          id: 3,
          movieId: "black-panther-wakanda-forever",
          title: "Black Panther: Wakanda Forever",
          image: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
          rating: "6.7",
          mood: ["emotional", "heroic", "tribute"],
        },
        {
          id: 4,
          movieId: "doctor-strange-2",
          title: "Doctor Strange 2",
          image: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
          rating: "6.9",
          mood: ["supernatural", "mind-bending", "action"],
        },
        {
          id: 5,
          movieId: "thor-love-and-thunder",
          title: "Thor: Love and Thunder",
          image: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
          rating: "6.2",
          mood: ["comedic", "colorful", "adventure"],
        },
        {
          id: 6,
          movieId: "minions-rise-of-gru",
          title: "Minions: The Rise of Gru",
          image: "https://image.tmdb.org/t/p/w500/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
          rating: "6.5",
          mood: ["family", "comedy", "animated"],
        },
        {
          id: 7,
          movieId: "everything-everywhere-all-at-once",
          title: "Everything Everywhere All at Once",
          image: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
          rating: "7.8",
          mood: ["mind-bending", "emotional", "surreal"],
        },
        {
          id: 8,
          movieId: "the-batman",
          title: "The Batman",
          image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
          rating: "7.8",
          mood: ["dark", "detective", "crime"],
        },
        {
          id: 107,
          movieId: "no-time-to-die",
          title: "No Time to Die",
          image: "https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
          rating: "7.3",
          mood: ["spy", "action", "bond"],
        },
        {
          id: 108,
          movieId: "dune",
          title: "Dune",
          image: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
          rating: "8.0",
          mood: ["epic", "sci-fi", "desert"],
        },
        {
          id: 109,
          movieId: "tenet",
          title: "Tenet",
          image: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
          rating: "7.3",
          mood: ["time", "complex", "action"],
        },
        {
          id: 110,
          movieId: "wonder-woman",
          title: "Wonder Woman",
          image: "https://image.tmdb.org/t/p/w500/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg",
          rating: "7.4",
          mood: ["heroic", "war", "empowering"],
        },
        {
          id: 111,
          movieId: "aquaman",
          title: "Aquaman",
          image: "https://image.tmdb.org/t/p/w500/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg",
          rating: "6.8",
          mood: ["underwater", "adventure", "dc"],
        },
        {
          id: 112,
          movieId: "shazam",
          title: "Shazam!",
          image: "https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
          rating: "7.0",
          mood: ["family", "superhero", "comedy"],
        },
        {
          id: 113,
          movieId: "joker",
          title: "Joker",
          image: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
          rating: "8.4",
          mood: ["dark", "psychological", "origins"],
        },
        {
          id: 114,
          movieId: "spider-man-no-way-home",
          title: "Spider-Man: No Way Home",
          image: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
          rating: "8.2",
          mood: ["multiverse", "nostalgic", "superhero"],
        },
        {
          id: 115,
          movieId: "eternals",
          title: "Eternals",
          image: "https://image.tmdb.org/t/p/w500/6AdXwFTRTAzggD2QUTt5B7JFGKL.jpg",
          rating: "6.3",
          mood: ["cosmic", "ensemble", "mythology"],
        },
        {
          id: 116,
          movieId: "venom-let-there-be-carnage",
          title: "Venom: Let There Be Carnage",
          image: "https://image.tmdb.org/t/p/w500/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
          rating: "5.9",
          mood: ["symbiote", "comedy", "anti-hero"],
        },
        {
          id: 117,
          movieId: "godzilla-vs-kong",
          title: "Godzilla vs. Kong",
          image: "https://image.tmdb.org/t/p/w500/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
          rating: "6.3",
          mood: ["kaiju", "epic", "monsters"],
        },
        {
          id: 118,
          movieId: "the-matrix-resurrections",
          title: "The Matrix Resurrections",
          image: "https://image.tmdb.org/t/p/w500/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
          rating: "5.7",
          mood: ["cyberpunk", "reality", "nostalgia"],
        },
        {
          id: 119,
          movieId: "fast-and-furious-9",
          title: "F9: The Fast Saga",
          image: "https://image.tmdb.org/t/p/w500/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
          rating: "5.2",
          mood: ["family", "cars", "over-the-top"],
        },
        {
          id: 120,
          movieId: "cruella",
          title: "Cruella",
          image: "https://image.tmdb.org/t/p/w500/rTh4K5uw9HypmpGslcKd4QfHl93.jpg",
          rating: "7.3",
          mood: ["fashion", "villain", "stylish"],
        },
        {
          id: 121,
          movieId: "luca",
          title: "Luca",
          image: "https://image.tmdb.org/t/p/w500/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
          rating: "7.4",
          mood: ["coming-of-age", "friendship", "italy"],
        }
      ]
    },
    {
      title: "Action & Adventure",
      movies: [
        {
          id: 9,
          movieId: "john-wick-chapter-4",
          title: "John Wick: Chapter 4",
          image: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
          rating: "7.7",
          mood: ["action", "stylish", "revenge"],
        },
        {
          id: 10,
          movieId: "fast-x",
          title: "Fast X",
          image: "https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
          rating: "5.8",
          mood: ["fast-paced", "family", "over-the-top"],
        },
        {
          id: 11,
          movieId: "mission-impossible-7",
          title: "Mission: Impossible 7",
          image: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
          rating: "7.7",
          mood: ["spy", "thrilling", "practical-stunts"],
        },
        {
          id: 12,
          movieId: "extraction-2",
          title: "Extraction 2",
          image: "https://image.tmdb.org/t/p/w500/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
          rating: "7.0",
          mood: ["intense", "military", "rescue"],
        },
        {
          id: 13,
          movieId: "indiana-jones-5",
          title: "Indiana Jones 5",
          image: "https://image.tmdb.org/t/p/w500/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
          rating: "6.5",
          mood: ["adventure", "nostalgic", "archaeology"],
        },
        {
          id: 14,
          movieId: "transformers-rise-of-beasts",
          title: "Transformers: Rise of the Beasts",
          image: "https://image.tmdb.org/t/p/w500/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
          rating: "6.0",
          mood: ["robots", "explosive", "90s"],
        },
        {
          id: 15,
          movieId: "guardians-galaxy-3",
          title: "Guardians of the Galaxy Vol. 3",
          image: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
          rating: "7.9",
          mood: ["emotional", "space", "soundtrack"],
        },
        {
          id: 16,
          movieId: "spider-man-across-spider-verse",
          title: "Spider-Man: Across the Spider-Verse",
          image: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
          rating: "8.7",
          mood: ["animated", "multiverse", "artistic"],
        },
        {
          id: 111,
          movieId: "mad-max-fury-road",
          title: "Mad Max: Fury Road",
          image: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
          rating: "8.1",
          mood: ["chase", "desert", "action"],
        },
        {
          id: 112,
          movieId: "the-raid",
          title: "The Raid",
          image: "https://image.tmdb.org/t/p/w500/yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
          rating: "7.6",
          mood: ["martial-arts", "intense", "building"],
        },
        {
          id: 113,
          movieId: "atomic-blonde",
          title: "Atomic Blonde",
          image: "https://image.tmdb.org/t/p/w500/kV9R5h0Yct1kR8Hf8sJ1nX0Vz4x.jpg",
          rating: "6.7",
          mood: ["spy", "80s", "stylish"],
        },
        {
          id: 114,
          movieId: "kingsman",
          title: "Kingsman: The Secret Service",
          image: "https://image.tmdb.org/t/p/w500/8x7ej61VEMHjwJYDpicxJcF3Ebv.jpg",
          rating: "7.7",
          mood: ["spy", "comedy", "stylish"],
        },
        {
          id: 115,
          movieId: "baby-driver",
          title: "Baby Driver",
          image: "https://image.tmdb.org/t/p/w500/rmnQ9jKW72bHu8uKlMjPIb2VLMI.jpg",
          rating: "7.6",
          mood: ["heist", "music", "cars"],
        }
      ]
    },
    {
      title: "Sci-Fi & Fantasy",
      movies: [
        {
          id: 17,
          movieId: "dune-part-two",
          title: "Dune: Part Two",
          image: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
          rating: "8.5",
          mood: ["epic", "desert", "prophecy"],
        },
        {
          id: 18,
          movieId: "blade-runner-2049",
          title: "Blade Runner 2049",
          image: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
          rating: "8.0",
          mood: ["cyberpunk", "philosophical", "visual"],
        },
        {
          id: 19,
          movieId: "interstellar",
          title: "Interstellar",
          image: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
          rating: "8.6",
          mood: ["space", "emotional", "science"],
        },
        {
          id: 20,
          movieId: "arrival",
          title: "Arrival",
          image: "https://image.tmdb.org/t/p/w500/tFQn9awdMlkg1fBrJObJOoNr8l3.jpg",
          rating: "7.9",
          mood: ["alien", "linguistic", "cerebral"],
        },
        {
          id: 21,
          movieId: "ex-machina",
          title: "Ex Machina",
          image: "https://image.tmdb.org/t/p/w500/btTdmkgIvOi0FFip1sPuZI2oQG6.jpg",
          rating: "7.7",
          mood: ["ai", "psychological", "thriller"],
        },
        {
          id: 22,
          movieId: "the-matrix-resurrections",
          title: "The Matrix Resurrections",
          image: "https://image.tmdb.org/t/p/w500/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
          rating: "5.7",
          mood: ["matrix", "reality", "action"],
        },
        {
          id: 23,
          movieId: "mad-max-fury-road",
          title: "Mad Max: Fury Road",
          image: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
          rating: "8.1",
          mood: ["post-apocalyptic", "chase", "practical"],
        },
        {
          id: 24,
          movieId: "alita-battle-angel",
          title: "Alita: Battle Angel",
          image: "https://image.tmdb.org/t/p/w500/xRWht48C2V8XNfzvPehyClOvDni.jpg",
          rating: "7.3",
          mood: ["cyborg", "action", "dystopian"],
        },
        {
          id: 116,
          movieId: "ready-player-one",
          title: "Ready Player One",
          image: "https://image.tmdb.org/t/p/w500/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
          rating: "7.4",
          mood: ["vr", "adventure", "nostalgia"],
        },
        {
          id: 117,
          movieId: "ghost-in-shell",
          title: "Ghost in the Shell",
          image: "https://image.tmdb.org/t/p/w500/myRzRzCxdfUWjkJWgpHHZ1oGkJd.jpg",
          rating: "6.3",
          mood: ["cyberpunk", "identity", "action"],
        },
        {
          id: 118,
          movieId: "elysium",
          title: "Elysium",
          image: "https://image.tmdb.org/t/p/w500/aUTAFOI2DEWEFzJxKu8YqZ6Y2z2.jpg",
          rating: "6.6",
          mood: ["dystopia", "space", "inequality"],
        },
        {
          id: 119,
          movieId: "district-9",
          title: "District 9",
          image: "https://image.tmdb.org/t/p/w500/isiKRmWd7VQGjpZl1mRbOuEmqg.jpg",
          rating: "7.9",
          mood: ["alien", "apartheid", "gritty"],
        },
        {
          id: 120,
          movieId: "pacific-rim",
          title: "Pacific Rim",
          image: "https://image.tmdb.org/t/p/w500/yCmySlVUAQsOPaKL9n6kUL5Uhqh.jpg",
          rating: "6.9",
          mood: ["robots", "kaiju", "epic"],
        }
      ]
    },
    {
      title: "Horror & Thriller",
      movies: [
        {
          id: 25,
          movieId: "scream-6",
          title: "Scream VI",
          image: "https://image.tmdb.org/t/p/w500/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
          rating: "6.5",
          mood: ["slasher", "meta", "legacy"],
        },
        {
          id: 26,
          movieId: "evil-dead-rise",
          title: "Evil Dead Rise",
          image: "https://image.tmdb.org/t/p/w500/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg",
          rating: "6.5",
          mood: ["demons", "gore", "apartment"],
        },
        {
          id: 27,
          movieId: "m3gan",
          title: "M3GAN",
          image: "https://image.tmdb.org/t/p/w500/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
          rating: "6.3",
          mood: ["ai-horror", "doll", "tech"],
        },
        {
          id: 28,
          movieId: "the-nun-2",
          title: "The Nun II",
          image: "https://image.tmdb.org/t/p/w500/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg",
          rating: "5.6",
          mood: ["supernatural", "convent", "demon"],
        },
        {
          id: 29,
          movieId: "insidious-red-door",
          title: "Insidious: The Red Door",
          image: "https://image.tmdb.org/t/p/w500/d07phJqCx6z5wILDYqkyraorDPi.jpg",
          rating: "5.5",
          mood: ["haunted", "family", "astral"],
        },
        {
          id: 30,
          movieId: "talk-to-me",
          title: "Talk to Me",
          image: "https://image.tmdb.org/t/p/w500/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
          rating: "7.1",
          mood: ["possession", "teens", "hand"],
        },
        {
          id: 31,
          movieId: "the-pope-exorcist",
          title: "The Pope's Exorcist",
          image: "https://image.tmdb.org/t/p/w500/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
          rating: "6.1",
          mood: ["exorcism", "vatican", "russell-crowe"],
        },
        {
          id: 32,
          movieId: "cocaine-bear",
          title: "Cocaine Bear",
          image: "https://image.tmdb.org/t/p/w500/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
          rating: "5.9",
          mood: ["dark-comedy", "bear", "drugs"],
        },
        {
          id: 121,
          movieId: "the-conjuring",
          title: "The Conjuring",
          image: "https://image.tmdb.org/t/p/w500/wVYREutYY5ljFMAAZGQOcUBg1mD.jpg",
          rating: "7.5",
          mood: ["supernatural", "family", "haunted"],
        },
        {
          id: 122,
          movieId: "hereditary",
          title: "Hereditary",
          image: "https://image.tmdb.org/t/p/w500/p8hOJPEAfqVOBbN3Y9cCIgmGX4Q.jpg",
          rating: "7.3",
          mood: ["psychological", "family", "disturbing"],
        },
        {
          id: 123,
          movieId: "midsommar",
          title: "Midsommar",
          image: "https://image.tmdb.org/t/p/w500/7LEI8ulZzIHJHkjJlANaCh7Cp6W.jpg",
          rating: "7.1",
          mood: ["cult", "bright", "disturbing"],
        },
        {
          id: 124,
          movieId: "get-out",
          title: "Get Out",
          image: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
          rating: "7.7",
          mood: ["social", "thriller", "mind-control"],
        },
        {
          id: 125,
          movieId: "us",
          title: "Us",
          image: "https://image.tmdb.org/t/p/w500/ux2dU1jQ2ACIMShzB3yP93Udpzc.jpg",
          rating: "6.8",
          mood: ["doppelganger", "family", "social"],
        }
      ]
    },
    {
      title: "Comedy",
      movies: [
        {
          id: 33,
          movieId: "barbie",
          title: "Barbie",
          image: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
          rating: "6.9",
          mood: ["pink", "satire", "musical"],
        },
        {
          id: 34,
          movieId: "oppenheimer",
          title: "Oppenheimer",
          image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
          rating: "8.4",
          mood: ["biographical", "drama", "imax"],
        },
        {
          id: 35,
          movieId: "air",
          title: "Air",
          image: "https://image.tmdb.org/t/p/w500/76AKQPdH3M8cvsFR9K8JsOzVlol.jpg",
          rating: "7.4",
          mood: ["basketball", "business", "80s"],
        },
        {
          id: 36,
          movieId: "puss-in-boots-2",
          title: "Puss in Boots: The Last Wish",
          image: "https://image.tmdb.org/t/p/w500/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
          rating: "7.8",
          mood: ["animated", "adventure", "death"],
        },
        {
          id: 37,
          movieId: "the-super-mario-bros-movie",
          title: "The Super Mario Bros. Movie",
          image: "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
          rating: "7.0",
          mood: ["nintendo", "family", "colorful"],
        },
        {
          id: 38,
          movieId: "80-for-brady",
          title: "80 for Brady",
          image: "https://image.tmdb.org/t/p/w500/jixBLmH4gQuEP15M1tWOZnvaLUl.jpg",
          rating: "5.8",
          mood: ["elderly", "football", "friendship"],
        },
        {
          id: 39,
          movieId: "scream-vi",
          title: "Ant-Man and the Wasp: Quantumania",
          image: "https://image.tmdb.org/t/p/w500/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
          rating: "6.1",
          mood: ["quantum", "family", "marvel"],
        },
        {
          id: 40,
          movieId: "dungeons-dragons",
          title: "Dungeons & Dragons: Honor Among Thieves",
          image: "https://image.tmdb.org/t/p/w500/A7AoNT06aRAc4SV89Dwxk5RYEDo.jpg",
          rating: "7.2",
          mood: ["fantasy", "adventure", "heist"],
        },
        {
          id: 126,
          movieId: "knives-out",
          title: "Knives Out",
          image: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
          rating: "7.9",
          mood: ["mystery", "comedy", "whodunit"],
        },
        {
          id: 127,
          movieId: "the-grand-budapest-hotel",
          title: "The Grand Budapest Hotel",
          image: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
          rating: "8.1",
          mood: ["quirky", "visual", "comedy"],
        },
        {
          id: 128,
          movieId: "jojo-rabbit",
          title: "Jojo Rabbit",
          image: "https://image.tmdb.org/t/p/w500/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
          rating: "7.9",
          mood: ["satire", "war", "coming-of-age"],
        },
        {
          id: 129,
          movieId: "once-upon-time-hollywood",
          title: "Once Upon a Time in Hollywood",
          image: "https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
          rating: "7.6",
          mood: ["nostalgia", "hollywood", "60s"],
        },
        {
          id: 130,
          movieId: "parasite",
          title: "Parasite",
          image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
          rating: "8.6",
          mood: ["social", "thriller", "class"],
        }
      ]
    },
    {
      title: "Drama",
      movies: [
        {
          id: 41,
          movieId: "the-whale",
          title: "The Whale",
          image: "https://image.tmdb.org/t/p/w500/jQ0gylJMxWSL490sy0RrPj9lmzI.jpg",
          rating: "7.7",
          mood: ["emotional", "redemption", "family"],
        },
        {
          id: 42,
          movieId: "women-talking",
          title: "Women Talking",
          image: "https://image.tmdb.org/t/p/w500/kIlOJ5NXKrBisyXYOTnH8mNpUn.jpg",
          rating: "6.9",
          mood: ["feminist", "discussion", "choice"],
        },
        {
          id: 43,
          movieId: "babylon",
          title: "Babylon",
          image: "https://image.tmdb.org/t/p/w500/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg",
          rating: "7.2",
          mood: ["hollywood", "decadent", "period"],
        },
        {
          id: 44,
          movieId: "the-fabelmans",
          title: "The Fabelmans",
          image: "https://image.tmdb.org/t/p/w500/d2pqiEJAW7GKPdJ6UMakXyFjeBa.jpg",
          rating: "7.5",
          mood: ["coming-of-age", "family", "filmmaking"],
        },
        {
          id: 45,
          movieId: "tar",
          title: "Tár",
          image: "https://image.tmdb.org/t/p/w500/dRVAlaU0vbG6hMf2K45NSiIyoUe.jpg",
          rating: "7.4",
          mood: ["classical", "power", "scandal"],
        },
        {
          id: 46,
          movieId: "aftersun",
          title: "Aftersun",
          image: "https://image.tmdb.org/t/p/w500/evKz85Ys3PjBmBGCak0mQGKTPzr.jpg",
          rating: "7.7",
          mood: ["memory", "father-daughter", "melancholy"],
        },
        {
          id: 47,
          movieId: "the-banshees-of-inisherin",
          title: "The Banshees of Inisherin",
          image: "https://image.tmdb.org/t/p/w500/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg",
          rating: "7.8",
          mood: ["friendship", "irish", "dark-comedy"],
        },
        {
          id: 48,
          movieId: "triangle-of-sadness",
          title: "Triangle of Sadness",
          image: "https://image.tmdb.org/t/p/w500/k3m9ocyx5xRx7rwvKbpKJhvKHns.jpg",
          rating: "7.2",
          mood: ["satire", "wealth", "yacht"],
        },
        {
          id: 131,
          movieId: "nomadland",
          title: "Nomadland",
          image: "https://image.tmdb.org/t/p/w500/2NjgOj6U6lBcjGTgG4uJ9YadMxl.jpg",
          rating: "7.3",
          mood: ["journey", "solitude", "america"],
        },
        {
          id: 132,
          movieId: "sound-of-metal",
          title: "Sound of Metal",
          image: "https://image.tmdb.org/t/p/w500/qcKgTqR8V1rAFTBV0ztTx5xNEyQ.jpg",
          rating: "7.7",
          mood: ["hearing-loss", "identity", "music"],
        },
        {
          id: 133,
          movieId: "minari",
          title: "Minari",
          image: "https://image.tmdb.org/t/p/w500/6BDHLhFPRiICAm3vn0JksEK4aAA.jpg",
          rating: "7.4",
          mood: ["family", "immigration", "farm"],
        },
        {
          id: 134,
          movieId: "promising-young-woman",
          title: "Promising Young Woman",
          image: "https://image.tmdb.org/t/p/w500/pKTW6jtOcAZJUSnf8o0llOAjRz5.jpg",
          rating: "7.2",
          mood: ["revenge", "feminist", "thriller"],
        },
        {
          id: 135,
          movieId: "the-father",
          title: "The Father",
          image: "https://image.tmdb.org/t/p/w500/pr3bEQ517uMb9PierLczCCk31yD.jpg",
          rating: "8.2",
          mood: ["dementia", "family", "emotional"],
        }
      ]
    },
    {
      title: "Marvel Universe",
      movies: [
        {
          id: 49,
          movieId: "wakanda-forever",
          title: "Black Panther: Wakanda Forever",
          image: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
          rating: "6.7",
          mood: ["tribute", "underwater", "legacy"],
        },
        {
          id: 50,
          movieId: "thor-4",
          title: "Thor: Love and Thunder",
          image: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
          rating: "6.2",
          mood: ["colorful", "jane-foster", "comedy"],
        },
        {
          id: 51,
          movieId: "strange-2",
          title: "Doctor Strange in the Multiverse of Madness",
          image: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
          rating: "6.9",
          mood: ["multiverse", "scarlet-witch", "horror"],
        },
        {
          id: 52,
          movieId: "eternals",
          title: "Eternals",
          image: "https://image.tmdb.org/t/p/w500/6AdXwFTRTAzggD2QUTt5B7JFGKL.jpg",
          rating: "6.3",
          mood: ["cosmic", "immortal", "ensemble"],
        },
        {
          id: 53,
          movieId: "no-way-home",
          title: "Spider-Man: No Way Home",
          image: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
          rating: "8.4",
          mood: ["multiverse", "nostalgia", "villains"],
        },
        {
          id: 54,
          movieId: "hawkeye-endgame",
          title: "Avengers: Endgame",
          image: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
          rating: "8.4",
          mood: ["epic", "finale", "emotional"],
        },
        {
          id: 55,
          movieId: "infinity-war",
          title: "Avengers: Infinity War",
          image: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
          rating: "8.4",
          mood: ["thanos", "stones", "dark"],
        },
        {
          id: 56,
          movieId: "shang-chi",
          title: "Shang-Chi and the Legend of the Ten Rings",
          image: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
          rating: "7.4",
          mood: ["martial-arts", "family", "asian"],
        }
      ]
    },
    {
      title: "DC Universe",
      movies: [
        {
          id: 57,
          movieId: "the-batman-2022",
          title: "The Batman",
          image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
          rating: "7.8",
          mood: ["noir", "detective", "riddler"],
        },
        {
          id: 58,
          movieId: "black-adam",
          title: "Black Adam",
          image: "https://image.tmdb.org/t/p/w500/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
          rating: "6.2",
          mood: ["antihero", "ancient", "power"],
        },
        {
          id: 59,
          movieId: "aquaman-2",
          title: "Aquaman and the Lost Kingdom",
          image: "https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
          rating: "5.7",
          mood: ["underwater", "adventure", "sequel"],
        },
        {
          id: 60,
          movieId: "wonder-woman-84",
          title: "Wonder Woman 1984",
          image: "https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
          rating: "5.4",
          mood: ["80s", "wish", "golden"],
        },
        {
          id: 61,
          movieId: "zack-snyder-justice-league",
          title: "Zack Snyder's Justice League",
          image: "https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
          rating: "8.0",
          mood: ["epic", "director-cut", "team"],
        },
        {
          id: 62,
          movieId: "the-suicide-squad",
          title: "The Suicide Squad",
          image: "https://image.tmdb.org/t/p/w500/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
          rating: "7.2",
          mood: ["anti-heroes", "comedy", "violent"],
        },
        {
          id: 63,
          movieId: "birds-of-prey",
          title: "Birds of Prey",
          image: "https://image.tmdb.org/t/p/w500/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
          rating: "6.1",
          mood: ["harley-quinn", "female", "colorful"],
        },
        {
          id: 64,
          movieId: "shazam-2",
          title: "Shazam! Fury of the Gods",
          image: "https://image.tmdb.org/t/p/w500/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
          rating: "5.9",
          mood: ["family", "mythology", "teen"],
        }
      ]
    },
    {
      title: "Animation",
      movies: [
        {
          id: 65,
          movieId: "turning-red",
          title: "Turning Red",
          image: "https://image.tmdb.org/t/p/w500/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
          rating: "7.0",
          mood: ["coming-of-age", "family", "panda"],
        },
        {
          id: 66,
          movieId: "encanto",
          title: "Encanto",
          image: "https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
          rating: "7.2",
          mood: ["family", "magic", "colombia"],
        },
        {
          id: 67,
          movieId: "luca",
          title: "Luca",
          image: "https://image.tmdb.org/t/p/w500/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
          rating: "7.4",
          mood: ["friendship", "italy", "sea-monster"],
        },
        {
          id: 68,
          movieId: "soul",
          title: "Soul",
          image: "https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
          rating: "8.0",
          mood: ["jazz", "purpose", "life"],
        },
        {
          id: 69,
          movieId: "strange-world",
          title: "Strange World",
          image: "https://image.tmdb.org/t/p/w500/fHMqfsYyl3hskL6wfxEJd9Sk0fE.jpg",
          rating: "5.7",
          mood: ["adventure", "family", "exploration"],
        },
        {
          id: 70,
          movieId: "lightyear",
          title: "Lightyear",
          image: "https://image.tmdb.org/t/p/w500/ox4goZd956BxqJH6iLwhWPL9ct4.jpg",
          rating: "5.1",
          mood: ["space", "toy-story", "origin"],
        },
        {
          id: 71,
          movieId: "onward",
          title: "Onward",
          image: "https://image.tmdb.org/t/p/w500/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
          rating: "7.4",
          mood: ["brotherhood", "magic", "quest"],
        },
        {
          id: 72,
          movieId: "coco",
          title: "Coco",
          image: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
          rating: "8.4",
          mood: ["family", "music", "mexican"],
        }
      ]
    },
    {
      title: "Classic Movies",
      movies: [
        {
          id: 73,
          movieId: "casablanca",
          title: "Casablanca",
          image: "https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSLezBOY0Qxh8a.jpg",
          rating: "8.5",
          mood: ["romance", "war", "classic"],
        },
        {
          id: 74,
          movieId: "citizen-kane",
          title: "Citizen Kane",
          image: "https://image.tmdb.org/t/p/w500/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg",
          rating: "8.3",
          mood: ["drama", "power", "american"],
        },
        {
          id: 75,
          movieId: "the-godfather",
          title: "The Godfather",
          image: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
          rating: "9.2",
          mood: ["crime", "family", "epic"],
        },
        {
          id: 76,
          movieId: "vertigo",
          title: "Vertigo",
          image: "https://image.tmdb.org/t/p/w500/15uOEfqBNTVtDUT7hGBVCka0jjt.jpg",
          rating: "8.3",
          mood: ["thriller", "psychological", "hitchcock"],
        },
        {
          id: 77,
          movieId: "singin-in-the-rain",
          title: "Singin' in the Rain",
          image: "https://image.tmdb.org/t/p/w500/w03EiJVHP8Un77nmvbHiuj0e8Fx.jpg",
          rating: "8.3",
          mood: ["musical", "comedy", "hollywood"],
        },
        {
          id: 78,
          movieId: "gone-with-the-wind",
          title: "Gone with the Wind",
          image: "https://image.tmdb.org/t/p/w500/lNz2HC1UkZUupDO9bRLNgYyda6e.jpg",
          rating: "8.1",
          mood: ["epic", "romance", "civil-war"],
        },
        {
          id: 79,
          movieId: "lawrence-of-arabia",
          title: "Lawrence of Arabia",
          image: "https://image.tmdb.org/t/p/w500/AiAm0EtDvyGqNpVoieRv4iJsOSV.jpg",
          rating: "8.3",
          mood: ["epic", "desert", "war"],
        },
        {
          id: 80,
          movieId: "the-wizard-of-oz",
          title: "The Wizard of Oz",
          image: "https://image.tmdb.org/t/p/w500/mxPeLmv4y2qhnHlbVH6xnPVb7dW.jpg",
          rating: "8.0",
          mood: ["fantasy", "musical", "family"],
        }
        ,
        {
          id: 105,
          movieId: "onward",
          title: "Onward",
          image: "https://image.tmdb.org/t/p/w500/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
          rating: "7.4",
          mood: ["brotherhood", "magic", "quest"],
        },
        {
          id: 106,
          movieId: "coco",
          title: "Coco",
          image: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
          rating: "8.4",
          mood: ["family", "music", "mexican"],
        }
      ]
    },
    {
      title: "International Cinema",
      movies: [
        {
          id: 81,
          movieId: "parasite",
          title: "Parasite",
          image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
          rating: "8.6",
          mood: ["thriller", "social", "korean"],
        },
        {
          id: 82,
          movieId: "oldboy",
          title: "Oldboy",
          image: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Quu.jpg",
          rating: "8.4",
          mood: ["revenge", "mystery", "korean"],
        },
        {
          id: 83,
          movieId: "spirited-away",
          title: "Spirited Away",
          image: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
          rating: "9.2",
          mood: ["animated", "fantasy", "ghibli"],
        },
        {
          id: 84,
          movieId: "seven-samurai",
          title: "Seven Samurai",
          image: "https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
          rating: "9.0",
          mood: ["epic", "samurai", "japanese"],
        },
        {
          id: 85,
          movieId: "8-1-2",
          title: "8½",
          image: "https://image.tmdb.org/t/p/w500/fW9zzJbhFAKRYD6LR0v2SyHX8vr.jpg",
          rating: "8.0",
          mood: ["surreal", "meta", "italian"],
        },
        {
          id: 86,
          movieId: "bicycle-thieves",
          title: "Bicycle Thieves",
          image: "https://image.tmdb.org/t/p/w500/62MNTZZOj4nQ85Nrh7QqB8G4y5.jpg",
          rating: "8.3",
          mood: ["neorealism", "social", "italian"],
        },
        {
          id: 87,
          movieId: "tokyo-story",
          title: "Tokyo Story",
          image: "https://image.tmdb.org/t/p/w500/g2YbTYKcl4SLvr18DgkBHSXJhIJ.jpg",
          rating: "8.2",
          mood: ["family", "aging", "japanese"],
        },
        {
          id: 88,
          movieId: "la-dolce-vita",
          title: "La Dolce Vita",
          image: "https://image.tmdb.org/t/p/w500/fR16ADqqZ6F2ypMhpJ7BSpUj8.jpg",
          rating: "8.1",
          mood: ["existential", "decadent", "italian"],
        }
      ]
    },
    // {
    //   title: "Documentary",
    //   movies: [
    //     {
    //       id: 89,
    //       movieId: "free-solo",
    //       title: "Free Solo",
    //       image: "https://image.tmdb.org/t/p/w500/zdqHHtVuJPGbUQyn2wJSSDfAjqT.jpg",
    //       rating: "8.1",
    //       mood: ["climbing", "extreme", "nature"],
    //     },
    //     {
    //       id: 90,
    //       movieId: "won-t-you-be-my-neighbor",
    //       title: "Won't You Be My Neighbor?",
    //       image: "https://image.tmdb.org/t/p/w500/gWI95ZwdGCn5yLWY0RlsGlO8V6t.jpg",
    //       rating: "8.4",
    //       mood: ["wholesome", "childhood", "mr-rogers"],
    //     },
    //     {
    //       id: 91,
    //       movieId: "march-of-the-penguins",
    //       title: "March of the Penguins",
    //       image: "https://image.tmdb.org/t/p/w500/9zOOKr8pxpP2QLTbDTgLR6m8TDP.jpg",
    //       rating: "7.5",
    //       mood: ["nature", "antarctica", "survival"],
    //     },
    //     {
    //       id: 92,
    //       movieId: "an-inconvenient-truth",
    //       title: "An Inconvenient Truth",
    //       image: "https://image.tmdb.org/t/p/w500/jJqEnCnE4cJJqA2ZjVvvWhtQODq.jpg",
    //       rating: "7.4",
    //       mood: ["climate", "education", "urgent"],
    //     },
    //     {
    //       id: 93,
    //       movieId: "bowling-for-columbine",
    //       title: "Bowling for Columbine",
    //       image: "https://image.tmdb.org/t/p/w500/6O3FYOLgDgtcXFMQ5xNMOxQYKHe.jpg",
    //       rating: "8.0",
    //       mood: ["guns", "america", "provocative"],
    //     },
    //     {
    //       id: 94,
    //       movieId: "fahrenheit-911",
    //       title: "Fahrenheit 9/11",
    //       image: "https://image.tmdb.org/t/p/w500/c1UwPrJolQvJ2ykYXFMHnHhUv5H.jpg",
    //       rating: "7.5",
    //       mood: ["political", "bush", "controversial"],
    //     },
    //     {
    //       id: 95,
    //       movieId: "the-social-dilemma",
    //       title: "The Social Dilemma",
    //       image: "https://image.tmdb.org/t/p/w500/uE8FNXv3hZKJ1T5Rx3fHhL3fQSs.jpg",
    //       rating: "7.6",
    //       mood: ["tech", "social-media", "warning"],
    //     },
    //     {
    //       id: 96,
    //       movieId: "my-octopus-teacher",
    //       title: "My Octopus Teacher",
    //       image: "https://image.tmdb.org/t/p/w500/bHhgeFEz5jvjLBWkJ6SYJBNn5rN.jpg",
    //       rating: "8.1",
    //       mood: ["ocean", "connection", "nature"],
    //     }
    //   ]
    // },
    {
      title: "Recently Added",
      movies: [
        {
          id: 97,
          movieId: "the-flash-2023",
          title: "The Flash",
          image: "https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
          rating: "6.7",
          mood: ["multiverse", "time-travel", "dc"],
        },
        {
          id: 98,
          movieId: "elemental",
          title: "Elemental",
          image: "https://image.tmdb.org/t/p/w500/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
          rating: "7.0",
          mood: ["elements", "love", "pixar"],
        },
        {
          id: 99,
          movieId: "asteroid-city",
          title: "Asteroid City",
          image: "https://image.tmdb.org/t/p/w500/qdq40gRS8xKnpFt5V75t6lUHgpx.jpg",
          rating: "6.5",
          mood: ["quirky", "desert", "wes-anderson"],
        },
        {
          id: 100,
          movieId: "past-lives",
          title: "Past Lives",
          image: "https://image.tmdb.org/t/p/w500/k3waqVXSnTiNVLTJZawang4dAar.jpg",
          rating: "7.8",
          mood: ["romance", "introspective", "korean"],
        },
        {
          id: 101,
          movieId: "killers-of-the-flower-moon",
          title: "Killers of the Flower Moon",
          image: "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
          rating: "7.6",
          mood: ["crime", "historical", "scorsese"],
        },
        {
          id: 102,
          movieId: "napoleon",
          title: "Napoleon",
          image: "https://image.tmdb.org/t/p/w500/vcZWJGvB5xydWuoGNdE2sq3g8tE.jpg",
          rating: "6.5",
          mood: ["historical", "war", "epic"],
        },
        {
          id: 103,
          movieId: "the-marvels",
          title: "The Marvels",
          image: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
          rating: "5.8",
          mood: ["superhero", "team", "cosmic"],
        },
        {
          id: 104,
          movieId: "poor-things",
          title: "Poor Things",
          image: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
          rating: "7.9",
          mood: ["surreal", "feminist", "victorian"],
        }
      ]
    }
  ]