AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Video Summarizer using Bedrock + Rekognition 

Globals:
  Function:
    Timeout: 900
    MemorySize: 2048
    Runtime: python3.10
    Environment:
      Variables:
        OUTPUT_BUCKET: !Ref OutputBucket
        NOVA_MODEL_ID: "amazon.nova-pro-v1:0"

Resources:
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ProcessVideoFunction.Arn

  OutputBucket:
    Type: AWS::S3::Bucket

  ProcessVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref InputBucket
        - S3WritePolicy:
            BucketName: !Ref OutputBucket
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*"
            - Effect: Allow
              Action: rekognition:*
              Resource: "*"

Outputs:
  InputBucketName:
    Value: !Ref InputBucket
  OutputBucketName:
    Value: !Ref OutputBucket
