// Movie names for recommendation system

const movieNames = [
  // Trending Now
  "Avatar: The Way of Water",
  "Top Gun: Maverick",
  "Black Panther: Wakanda Forever",
  "Doctor Strange 2",
  "Thor: Love and Thunder",
  "Minions: The Rise of Gru",
  "Everything Everywhere All at Once",
  "The Batman",
  "No Time to Die",
  "Dune",
  "Tenet",
  "Wonder Woman",
  "Aquaman",
  "Shazam!",
  "Joker",
  "Spider-Man: No Way Home",
  "Eternals",
  "Venom: Let There Be Carnage",
  "Godzilla vs. Kong",
  "The Matrix Resurrections",
  "F9: The Fast Saga",
  "Cruella",
  "Luca",

  // Action & Adventure
  "John Wick: Chapter 4",
  "Fast X",
  "Mission: Impossible 7",
  "Extraction 2",
  "Indiana Jones 5",
  "Transformers: Rise of the Beasts",
  "Guardians of the Galaxy Vol. 3",
  "Spider-Man: Across the Spider-Verse",
  "Mad Max: Fury Road",
  "The Raid",
  "Atomic Blonde",
  "Kingsman: The Secret Service",
  "Baby Driver",

  // Sci-Fi & Fantasy
  "Dune: Part Two",
  "Blade Runner 2049",
  "Interstellar",
  "Arrival",
  "Ex Machina",
  "Alita: Battle Angel",
  "Ready Player One",
  "Ghost in the Shell",
  "Elysium",
  "District 9",
  "Pacific Rim",

  // Horror & Thriller
  "Scream VI",
  "Evil Dead Rise",
  "M3GAN",
  "The Nun II",
  "Insidious: The Red Door",
  "Talk to Me",
  "The Pope's Exorcist",
  "Cocaine Bear",
  "The Conjuring",
  "Hereditary",
  "Midsommar",
  "Get Out",
  "Us",

  // Comedy
  "Barbie",
  "Oppenheimer",
  "Air",
  "Puss in Boots: The Last Wish",
  "The Super Mario Bros. Movie",
  "80 for Brady",
  "Ant-Man and the Wasp: Quantumania",
  "Dungeons & Dragons: Honor Among Thieves",
  "Knives Out",
  "The Grand Budapest Hotel",
  "Jojo Rabbit",
  "Once Upon a Time in Hollywood",
  "Parasite",

  // Marvel Universe
  "Shang-Chi and the Legend of the Ten Rings",
  "Black Widow",
  "Captain Marvel",
  "Ant-Man and the Wasp",
  "Avengers: Endgame",
  "Avengers: Infinity War",

  // DC Universe
  "Black Adam",
  "Aquaman and the Lost Kingdom",
  "Wonder Woman 1984",
  "Zack Snyder's Justice League",
  "The Suicide Squad",
  "Birds of Prey",
  "Shazam! Fury of the Gods",
  "Man of Steel",
  "Justice League",

  // Animation
  "Turning Red",
  "Encanto",
  "Soul",
  "Strange World",
  "Lightyear",
  "Onward",
  "Coco",
  "Zootopia",
  "Moana",
  "How to Train Your Dragon",

  // Classic Movies
  "Casablanca",
  "Citizen Kane",
  "The Godfather",
  "Vertigo",
  "Singin' in the Rain",
  "Gone with the Wind",
  "Lawrence of Arabia",
  "The Wizard of Oz",

  // International Cinema
  "Oldboy",
  "Spirited Away",
  "Seven Samurai",
  "8½",
  "Bicycle Thieves",
  "Tokyo Story",
  "La Dolce Vita",

  // Recently Added
  "The Flash",
  "Elemental",
  "Asteroid City",
  "Past Lives",
  "Killers of the Flower Moon",
  "Napoleon",
  "The Marvels",
  "Poor Things"
];

module.exports = { movieNames };
