// Export movieCategories array for shared use

export const movieCategories = [
    {
      title: "Trending Now",
      movies: [
        {
          id: 1,
          movieId: "avatar-way-of-water",
          title: "Avatar: The Way of Water",
          image: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
          rating: "7.6",
          mood: ["epic", "visual-spectacle", "adventure"],
        },
        {
          id: 2,
          movieId: "top-gun-maverick",
          title: "Top Gun: Maverick",
          image: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
          rating: "8.3",
          mood: ["adrenaline", "nostalgic", "action-packed"],
        },
        {
          id: 3,
          movieId: "black-panther-wakanda-forever",
          title: "Black Panther: Wakanda Forever",
          image: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
          rating: "6.7",
          mood: ["emotional", "heroic", "tribute"],
        },
        {
          id: 4,
          movieId: "doctor-strange-2",
          title: "Doctor Strange 2",
          image: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
          rating: "6.9",
          mood: ["supernatural", "mind-bending", "action"],
        },
        {
          id: 5,
          movieId: "thor-love-and-thunder",
          title: "Thor: Love and Thunder",
          image: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
          rating: "6.2",
          mood: ["comedic", "colorful", "adventure"],
        },
        {
          id: 6,
          movieId: "minions-rise-of-gru",
          title: "Minions: The Rise of Gru",
          image: "https://image.tmdb.org/t/p/w500/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
          rating: "6.5",
          mood: ["funny", "family-friendly", "lighthearted"],
        },
        {
          id: 7,
          movieId: "jurassic-world-dominion",
          title: "Jurassic World Dominion",
          image: "https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
          rating: "5.6",
          mood: ["thrilling", "adventure", "nostalgic"],
        },
        {
          id: 8,
          movieId: "lightyear",
          title: "Lightyear",
          image: "https://image.tmdb.org/t/p/w500/ox4goZd956BxqJH6iLwhWPL9ct4.jpg",
          rating: "5.1",
          mood: ["adventure", "family-friendly", "space"],
        },
      ],
    },
    {
      title: "New Releases",
      movies: [
        {
          id: 11,
          movieId: "the-batman",
          title: "The Batman",
          image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
          rating: "7.8",
          mood: ["dark", "gritty", "detective"],
        },
        {
          id: 12,
          movieId: "dune",
          title: "Dune",
          image: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
          rating: "8.0",
          mood: ["epic", "sci-fi", "visually-stunning"],
        },
        {
          id: 13,
          movieId: "no-time-to-die",
          title: "No Time to Die",
          image: "https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
          rating: "7.3",
          mood: ["action", "spy", "emotional"],
        },
        {
          id: 14,
          movieId: "spider-man-no-way-home",
          title: "Spider-Man: No Way Home",
          image: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
          rating: "8.4",
          mood: ["nostalgic", "action", "multiverse"],
        },
        {
          id: 15,
          movieId: "the-french-dispatch",
          title: "The French Dispatch",
          image: "https://image.tmdb.org/t/p/w500/4NjNKCT9nRmRCtJEyJGJZZWTYVt.jpg",
          rating: "7.1",
          mood: ["quirky", "artistic", "whimsical"],
        },
        {
          id: 16,
          movieId: "eternals",
          title: "Eternals",
          image: "https://image.tmdb.org/t/p/w500/lFByFSLV5WDJEv3KabbdAF959F2.jpg",
          rating: "6.3",
          mood: ["epic", "cosmic", "philosophical"],
        },
        {
          id: 17,
          movieId: "house-of-gucci",
          title: "House of Gucci",
          image: "https://image.tmdb.org/t/p/w500/jPQdK7vdre5gTvdYcpSMGW4CR2d.jpg",
          rating: "6.6",
          mood: ["dramatic", "luxurious", "crime"],
        },
        {
          id: 18,
          movieId: "the-power-of-the-dog",
          title: "The Power of the Dog",
          image: "https://image.tmdb.org/t/p/w500/kEy48iCzGnp0ao1cZbNeWR6yIhC.jpg",
          rating: "6.8",
          mood: ["psychological", "slow-burn", "western"],
        },
      ],
    },
    {
      title: "Popular on FireStream",
      movies: [
        {
          id: 21,
          movieId: "stranger-things",
          title: "Stranger Things",
          image: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
          rating: "8.7",
          mood: ["nostalgic", "supernatural", "friendship"],
        },
        {
          id: 22,
          movieId: "the-witcher",
          title: "The Witcher",
          image: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
          rating: "8.2",
          mood: ["fantasy", "dark", "adventure"],
        },
        {
          id: 23,
          movieId: "ozark",
          title: "Ozark",
          image: "https://image.tmdb.org/t/p/w500/m73QiJOFyQIDdw3pXTZkJYExZpN.jpg",
          rating: "8.4",
          mood: ["tense", "crime", "family-drama"],
        },
        {
          id: 24,
          movieId: "the-crown",
          title: "The Crown",
          image: "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg",
          rating: "8.6",
          mood: ["historical", "dramatic", "royal"],
        },
        {
          id: 25,
          movieId: "bridgerton",
          title: "Bridgerton",
          image: "https://image.tmdb.org/t/p/w500/luoKpgVi1E5nQsi7W0UuKHu2Rq.jpg",
          rating: "7.3",
          mood: ["romantic", "period", "steamy"],
        },
        {
          id: 26,
          movieId: "money-heist",
          title: "Money Heist",
          image: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
          rating: "8.3",
          mood: ["heist", "intense", "strategic"],
        },
        {
          id: 27,
          movieId: "the-queens-gambit",
          title: "The Queen's Gambit",
          image: "https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
          rating: "8.5",
          mood: ["inspiring", "chess", "coming-of-age"],
        },
        {
          id: 28,
          movieId: "squid-game",
          title: "Squid Game",
          image: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
          rating: "8.0",
          mood: ["intense", "survival", "social-commentary"],
        },
      ],
    },
  ];
